### ISSUE TITLE
ALIAS.py list index out of range

### ISSUE THREAD

**Issue by na3na3na** [Nauchnik/alias#1]
Hello,

Im running into index errrors when running alias_ls.

It was ran with the following command on a 256 core cpu:
./alias_ls ../test/ASG_72_keystream76_0.cnf -pcs=../test/first72vars.pcs -solver=genipainterval-picosat961 

The error message is as follows
IndexError: list index out of range
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
  result = (True, func(*args, ** kwds))
File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
  return list(map(*args))
File "ALIAS.py", line 497, in run)sampler
  tmp[1]=int(tmp[1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "ALIAS.py", line 753, in <module>
  ALIAS_estimate()
File "ALIAS.py", line 551, in ALIAS_estimate
  files = multiprocess_run_sampler(big_sampling_dict)
File "ALIAS.py", line 506, in multiprocess_run_sampler
  p_res = p.map(run_sampler,sampling_inputs)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
  return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
  raise self._value
IndexError: list index out of range

**Comment by veinamond** [comment]
Hello.
It has been a while since we last checked on the repository condition. We will try to fix the issue you outlined in the nearest future, time permitting.
